server:
  port: 8888

spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/ohbyungkwon/msa-config-store.git
          #username: !!!!
          #passphrase: !!!
          #uri: file://Users/obyeong-gwon/git-local-repo

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, bus-refresh, env